server:
  port: 8080
spring:
  servlet:
    multipart:
      # Spring Boot???????????????ServletFileUpload?????Spring Boot?????
      enabled: false
      # ????????
      max-file-size: 1GB
      # ????????????
      max-request-size: 10GB
